default_agent: customer_support_agent
agents:
  CustomerSupportAgent:
    name: CustomerSupportAgent
    language: python
    node_version: '20'
    entrypoint: C:/Users/nidhi/OneDrive/Desktop/AIMLSCHOLAR P2/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\nidhi\OneDrive\Desktop\AIMLSCHOLAR P2
    aws:
      execution_role: arn:aws:iam::041058731288:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-1687b1c02b
      execution_role_auto_create: false
      account: 041058731288
      region: us-east-1
      ecr_repository: 041058731288.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-customersupportagent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: CustomerSupportMemory-sRFaSh6LsL
      memory_arn: null
      memory_name: CustomerSupportMemory-sRFaSh6LsL
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  customer_support_agent:
    name: customer_support_agent
    language: python
    node_version: '20'
    entrypoint: C:/Users/nidhi/OneDrive/Desktop/AIMLSCHOLAR P2/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: C:\Users\nidhi\OneDrive\Desktop\AIMLSCHOLAR P2
    aws:
      execution_role: arn:aws:iam::041058731288:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-1687b1c02b
      execution_role_auto_create: false
      account: 041058731288
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-041058731288-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: customer_support_agent-7h5E8b8lYM
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:041058731288:runtime/customer_support_agent-7h5E8b8lYM
      agent_session_id: browser-test-987654321000000000000000000
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: CustomerSupportMemory-sRFaSh6LsL
      memory_arn: null
      memory_name: CustomerSupportMemory-sRFaSh6LsL
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
